### ISSUE TITLE
i KNOW THIS IS DEPRECATED

### ISSUE THREAD

**Issue by inY2K** [michaelsboost/WebDGap#11]
But could you help me out real quick :)

If I add an app where users have to scroll down, how can I allow this to happen? It seems like  WebDGap remove all scrolling functionalities!

Thanks

**Comment by michaelsboost** [comment]
I am using JQuery’s [.scrollTop](https://api.jquery.com/scrollTop/) method. 

    $("html, body").animate({ scrollTop: $(".chosenbit").offset().top }, "slow");
