### ISSUE TITLE
[Q] Run local webserver [enhancement]

### ISSUE THREAD

**Issue by chezyann** [michaelsboost/WebDGap#3]
Hello,

First, thank you very much for your very useful tool :)

Second, I'm trying to make a desktop application for some dynamic website using XMLHttpRequests to dynamically load data. As a consequence I need to run it on an http server for XMLHttpRequests not to be rejected (Cross-origin AJAX request problem). What I can do presently is to use Python3 in the website root directory : `python -m http.server 8887` to start a webserver after what I can use the WebDGap converted application by editing /data/content/index.html to load `http://127.0.0.1:8887/` in its iframe.

Would it be possible to add a checkbox in WebDGap to make the desktop application running a webserver before loading the web application ?

Best regards

**Comment by mikethedj4** [comment]
I apologize for the late reply. 
WebDGap uses a precompiled version of nwjs + nodejs. 
That's currently not possible with the way WebDGap is developed.
