### ISSUE TITLE
can't run exe file

### ISSUE THREAD

**Issue by guinevere19** [michaelsboost/WebDGap#9]
Hello,

I could create a desktop app from my html file successfully. But the link to the exe file(like notepad.exe) didn't work. It was working in IE not chrome. Here is the code.

 <script type="text/javascript" language="javascript">
        function RunFile() {
		WshShell = new ActiveXObject("WScript.Shell");
		WshShell.Run("c:/windows/system32/notepad.exe", 1, false);
        }
    </script>

<body>
<a href="#" onClick="RunFile();">Notepad</a>
</body>

Please help me!

**Comment by michaelsboost** [comment]
That looks like VBScript. NW.JS which is the wrapper WebDGap's desktop apps use does not support VBScript. They run off of a WebKit js rendering engine. 

You will need to review the <a href="https://github.com/nwjs/nw.js/wiki/how-to-run-apps">"How to run apps"</a> guide from NW.js to run notepad.exe
